[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.tailwindcss-ls.config.userLanguages]
rust = "html"
"*.rs" = "html"
