[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
formatter = { command = 'deno', args = ["fmt", "-", "--line-width", "120", "--ext", "md" ] }

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.tailwindcss-ls.config.userLanguages]
rust = "html"
"*.rs" = "html"
