show_selection_mark = true
icon_theme = "nerdfont"

imports = [
  "verbs.toml",
  "skins/native-16.toml",
]

[special-paths]
"/media" = { list = "never", sum = "never" }
"~/.config" = { show = "always" }
"trav" = { show = "always", list = "always", sum = "never" }
# "~/useless" = { show = "never" }
# "~/my-link-I-want-to-explore" = { list = "always" }
