###############################################################
# This file contains the verb definitions for broot
#
# Some verbs here are examples and not enabled by default: you
#  need to uncomment them if you want to use them.
#
# Documentation at https://dystroy.org/broot/verbs/
###############################################################

# You should customize this standard opening of text files.
# If you edit text files in your terminal (vi, emacs, helix, eg.), then
#  you'll find it convenient to change the 'key' from 'ctrl-e' to 'enter'.
#
# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
#    export EDITOR=/usr/local/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# If your editor is able to open a file on a specific line, use {line}
#  so that you may jump directly at the right line from a preview or
#  a content search.
# Examples depending on your favourite editor:
#    execution: "nvim +{line} {file}"
#    execution: "helix {file}:{line}"
[[verbs]]
apply_to = "text_file"
execution = 'nu --login --commands "wz open {file}:{line}"'
invocation = "edit"
key = "enter"
leave_broot = false
shortcut = "e"

# A convenient shortcut to create new text files in
#  the current directory or below
[[verbs]]
execution = "$EDITOR {directory}/{subpath}"
invocation = "create {subpath}"
leave_broot = false

[[verbs]]
execution = "git difftool -y {file}"
invocation = "git_diff"
leave_broot = false
shortcut = "gd"

# On ctrl-b, propose the creation of a copy of the selection.
# While this might occasionally be useful, this verb is mostly here
# as an example to demonstrate rare standard groups like {file-stem}
# and {file-dot-extension} and the auto_exec verb property which
# allows verbs to stay unexecuted until you hit enter
[[verbs]]
auto_exec = false
execution = "cp -r {file} {parent}/{file-stem}-{version}{file-dot-extension}"
invocation = "backup {version}"
key = "ctrl-b"
leave_broot = false

# This verb lets you launch a terminal on ctrl-T
# (on exit you'll be back in broot)
[[verbs]]
execution = "$SHELL"
invocation = "terminal"
key = "ctrl-t"
leave_broot = false
set_working_dir = true
