[helpers]

[default]
depends = []

[default.files]
git = "~/.config/git"

[arch.files]
pacdef = "~/.config/pacdef"
paru = "~/.config/paru"

[mac.files]
homebrew = "~/.config/homebrew"
"mac/LaunchAgents" = "~/Library/LaunchAgents"

[broot.files]
broot = "~/.config/broot"

[bash.files]
bashrc = "~/.bashrc"

[gitui.files]
gitui = "~/.config/gitui"

[gpg.files]
gnupg = "~/.local/share/gnupg"

[helix.files]
helix = "~/.config/helix"

[nu.files]
nushell = "~/.config/nushell"

[wayland.files]
fuzzel = "~/.config/fuzzel"
icons = "~/.local/share/icons"
niri = "~/.config/niri"
swaylock = "~/.config/swaylock"
swaync = "~/.config/swaync"
waybar = "~/.config/waybar"

[wezterm.files]
wezterm = "~/.config/wezterm"
