[helpers]

[default]
depends = []

[default.files]
git = "~/.config/git"

[default.variables]
email = "00.pavers_dither@icloud.com"

[arch.files]
pacdef = "~/.config/pacdef"
paru = "~/.config/paru"

[bash.files]
bashrc = "~/.bashrc"

[bat.files]
bat = "~/.config/bat"
".bat/themes" = "~/.config/bat/themes"

[fuzzel.files]
fuzzel = "~/.config/fuzzel"

[gitui.files]
gitui = "~/.config/gitui"

[helix.files]
helix = "~/.config/helix"

[niri.files]
niri = "~/.config/niri"

[nu.files]
nushell = "~/.config/nushell"

[streamlink.files]
streamlink = "~/.config/streamlink"

[wayland.files]
swaylock = "~/.config/swaylock"
swaync = "~/.config/swaync"
waybar = "~/.config/waybar"
".waybar/themes" = "~/.config/waybar"
waypaper = "~/.config/waypaper"

[wezterm.files]
wezterm = "~/.config/wezterm"

[yazi.files]
yazi = "~/.config/yazi"
