[helpers]

[default]
depends = []

[default.files]
git = "~/.config/git"

[arch.files]
pacdef = "~/.config/pacdef"
paru = "~/.config/paru"

[mac.files]
homebrew = "~/.config/homebrew"
"mac/LaunchAgents" = "~/Library/LaunchAgents"

[bash.files]
bashrc = "~/.bashrc"

[fuzzel.files]
fuzzel = "~/.config/fuzzel"

[gitui.files]
gitui = "~/.config/gitui"

[helix.files]
helix = "~/.config/helix"

[niri.files]
niri = "~/.config/niri"

[nu.files]
nushell = "~/.config/nushell"

[streamlink.files]
streamlink = "~/.config/streamlink"

[wayland.files]
swaylock = "~/.config/swaylock"
swaync = "~/.config/swaync"
waybar = "~/.config/waybar"
".waybar/themes" = "~/.config/waybar"
waypaper = "~/.config/waypaper"

[wezterm.files]
wezterm = "~/.config/wezterm"
