includes = []
packages = [
  "broot",
  "gitui",
  "gpg",
  "helix",
  "nu",
  "wezterm",
]

[files]
broot = "~/AppData/Roaming/dystroy/broot/config"
gitui = "~/AppData/Roaming/gitui"
gnupg = "~/scoop/persist/gpg/home"
helix = "~/AppData/Roaming/helix"
"wezterm/wezterm.lua" = "~/.wezterm.lua"

[variables]
