includes = []
packages = [
  "gitui",
  "gpg",
  "helix",
  "nu",
  "wezterm",
]

[files]
gitui = "~/AppData/Roaming/gitui"
gnupg = "~/scoop/persist/gpg/home"
helix = "~/AppData/Roaming/helix"
nushell = "~/AppData/Roaming/nushell"
"wezterm/wezterm.lua" = "~/.wezterm.lua"

[variables]
